//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_LABORAL
    {
        public long LLAVE_EXP_LAB { get; set; }
        public Nullable<long> LLAVE_USUARIO { get; set; }
        public string PUESTO { get; set; }
        public string FUNCIONES { get; set; }
        public string EMPRESA { get; set; }
        public Nullable<int> NO_EMPLEADOS { get; set; }
        public string FECHA_INICIO { get; set; }
        public string FECHA_FIN { get; set; }
        public Nullable<long> RET_MENS_BRUTA { get; set; }
        public Nullable<long> RET_MENS_NETA { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string PAIS { get; set; }
        public Nullable<long> LLAVE_DATO_PERSONAL { get; set; }
    }
}
