//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public long LLAVE_USUARIO { get; set; }
        public string USUARIO { get; set; }
        public string PASS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
    }
}
